name: ezstate
description: Easy State Manager for Flutter
publish_to: 'none'
version: 0.0.2

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
