name: ezstate
description: Easy State Manager for Flutter
publish_to: 'none'
version: 0.0.3

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
